---
config:
  transport: ssh
  ssh:
    user: centos
    host-key-check: false
    run-as: root

nodes:
  - name: ec2-52-32-128-163.us-west-2.compute.amazonaws.com
    alias: search_head
    vars:
      addons:
        - name: Splunk_TA_nix
          filename: splunk-add-on-for-unix-and-linux_602.tgz
          inputs:
            monitor:///var/log:
              whitelist: (\.log|log$|messages|secure|auth|mesg$|cron$|acpid$|\.out)
              blacklist: (lastlog|anaconda\.syslog)
              disabled:  false
            script://./bin/uptime.sh:
              interval:   86400
              source:     Unix:Uptime
              sourcetype: Unix:Uptime
              disabled:   false
          additional_settings:
            is_configured:
              filename: app.conf
              section: install
              value: true
        - name: splunk_app_for_nix
          filename: splunk-app-for-unix-and-linux_525.tgz
          additional_settings:
            is_configured:
              filename: app.conf
              section: install
              value: true
  - name: ec2-54-214-200-239.us-west-2.compute.amazonaws.com
    alias: forwarder0
  - name: ec2-54-244-108-52.us-west-2.compute.amazonaws.com
    alias: forwarder1
  - name: ec2-34-221-60-234.us-west-2.compute.amazonaws.com
    alias: forwarder2
  - name: ec2-34-220-235-28.us-west-2.compute.amazonaws.com
    alias: forwarder3
  - name: ec2-35-162-56-240.us-west-2.compute.amazonaws.com
    alias: forwarder4

groups:
  - name: forwarders
    nodes:
      - forwarder0
      - forwarder1
      - forwarder2
      - forwarder3
      - forwarder4
    vars:
      addons:
        - name: Splunk_TA_nix
          filename: splunk-add-on-for-unix-and-linux_602.tgz
          inputs:
            monitor:///var/log:
              whitelist: (\.log|log$|messages|secure|auth|mesg$|cron$|acpid$|\.out)
              blacklist: (lastlog|anaconda\.syslog)
              disabled:  false
            script://./bin/uptime.sh:
              interval:   86400
              source:     Unix:Uptime
              sourcetype: Unix:Uptime
              disabled:   false
          additional_settings:
            is_configured:
              filename: app.conf
              section: install
              value: true
